name: Update Trackers

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:  # 添加权限设置
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:  # 添加 token 参数
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run merger script
      run: python merge_trackers.py
      
    - name: Commit and Push
      uses: ad-m/github-push-action@v0.6.0  # 使用专门推送的 Action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
